name: "CD"
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2

      - run: npm install
      - run: npm run build
      - run: cp -r blobs/ dist/blobs/
      
      # Remove bundled js
      - run: rm -rf dist/bundled-js/
      - run: find . -type f -name '*.html' -exec sed -i '/bundled-js/d' {} \;

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
